# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 171b8d751ada39023fc3989e4008a66f543f48f079e680f0637485ec51163bef992adfced666030122429319162935a08cab5d9f1de61be8512ea0b67c1804f7

test:
  secret_key_base: 699f7d0753baced9441d9a24afa958d766bd43f71d6bf7cd676e42dbb26f2fc33c54a1b40ab16d3c2d7a4332a0bacc8c35bb6a930c658ef31fc49e0dc5571e82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
